import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

export const historialStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
  },
  headerIcon: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    padding: 10,
  },
  headerTitulo: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.primary,
  },
  headerSubtitulo: {
    fontSize: 14,
    color: "#64748b",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: COLORS.textHeading,
  },
  emptyContainer: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 16,
  },
  emptyIconBox: {
    backgroundColor: "#f1f5f9",
    padding: 18,
    borderRadius: 50,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    color: COLORS.textHeading,
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 13,
    color: "#64748b",
    textAlign: "center",
    marginBottom: 20,
  },
  primaryButton: {
    flexDirection: "row",
    backgroundColor: "#0f172a",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
  reporteCard: {
    backgroundColor: "white",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 1,
  },
  reporteInfo: {
    flex: 1,
  },
  reporteCliente: {
    fontWeight: "600",
    fontSize: 16,
    textTransform: "capitalize",
    marginBottom: 6,
    color: COLORS.textHeading,
  },
  reporteDetalle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  reporteTexto: {
    color: COLORS.slate,
    fontSize: 13,
  },
  reporteBotones: {
    alignItems: "center",
    gap: 12,
  },
  btnDescargar: {
    backgroundColor: "#f1f5f9",
    padding: 8,
    borderRadius: 8,
    width: 50,
    alignItems: "center",
  },
  btnEliminar: {
    backgroundColor: "#fee2e2",
    padding: 8,
    borderRadius: 8,
    width: 50,
    alignItems: "center",
  },
  sinReportes: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 80,
  },
  sinReportesTexto: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.slate,
    marginTop: 10,
  },
  sinReportesSub: {
    color: "#94a3b8",
    fontSize: 13,
    textAlign: "center",
    marginVertical: 10,
  },
  btnCrear: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    marginTop: 8,
    gap: 6,
  },
  btnCrearTexto: {
    color: "white",
    fontWeight: "500",
  },
});